spring.application.name=crud-generation
spring.datasource.url=jdbc:postgresql://localhost:5432/vol
spring.datasource.username=vol
spring.datasource.password=123
spring.datasource.driver-class-name=org.postgresql.Driver

group=com.eval.itu